server:

  port: 8090

spring:
  profiles:
    active: local
  output:
    ansi:
      enabled: ALWAYS
  jmx:
    enabled: false
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: ${S3_BUCKET}
        base-url: ${S3_BASE_URL}
      region:
        static: sa-east-1
#        ${S3_REGION}
      stack:
        auto: false
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: matchon2025@gmail.com
    password: javgtcewnxkwnzmy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false


app:
  domain-url: http://localhost:8090

matchon:
  kakao-api: ${KAKAO_API_KEY}
  dialogflow-key-path:  ${DIALOGFLOW_KEY_PATH}
#  /app/keys/dialogflow-key.json
#  ${DIALOGFLOW_KEY_PATH}
jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show_sql: true
  output:
    ansi:
      enabled: ALWAYS
  security:
    user:
      name: user
      password: 1234
      roles: USER
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
file:
  upload-dir: C:/upload-dir

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_PROD_URL}
    username: ${DB_PROD_USER}
    password: ${DB_PROD_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show_sql: false
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB







